"""rename department

Revision ID: 8d199fbf9d2a
Revises: 48e6f73d10f2
Create Date: 2023-11-13 20:08:45.830560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d199fbf9d2a'
down_revision = '48e6f73d10f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
